spring:
  rabbitmq:
    listener:
      simple:
        retry:
          enabled: false
    template:
      reply-timeout: 15000
      retry:
        enabled: false
  jackson:
    serialization:
      write_dates_as_timestamps: false
  application:
    name: calendar-service
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true


server:
  port: 9103

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://eureka:8761/eureka/
  instance:
    hostname: calendar-service

logging:
  level:
    com:
      netflix:
        eureka: INFO
        discovery: INFO