server:
  port: 8762

spring:
  application:
    name: zuul-server


zuul:
  host:
    socket-timeout-millis: 120000
    connect-timeout-millis: 120000
  ignoredServices: '*'
  routes:
    authService:
      path: /auth/**
      serviceId: auth-service
      stripPrefix: false
      sensitiveHeaders: Cookie,Set-Cookie
    userService:
      path: /users/**
      serviceId: user-service
      stripPrefix: false
    groupService:
      path: /groups/**
      serviceId: group-service
      stripPrefix: false
    calendarService:
      path: /calendar/**
      serviceId: calendar-service
      stripPrefix: false
    notificationService:
      path: /notification/**
      serviceId: notification-service
      stripPrefix: false

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://eureka:8761/eureka/
  instance:
    hostname: zuul


ribbon:
  ReadTimeout: 120000


logging:
  level:
    org:
      springframework:
        cloud:
          netflix: INFO

